// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: string;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type AuthResponse = {
  jwt: string;
  user: User;
};

/*==========Testing zone==========*/
export type Pagination = {
  total: number;
  page: number;
  limit: number;
  nextUrl: string;
};

export type User = {
  id: number;
  username: string;
  email: string;
  bio: string;
  avatar: string;
  coverImage: string;
  achievement: {
    karma: number;
    badge: string;
    totalPosts: number;
    totalComments: number;
  };
  createdAt: string;
  role: string;
};

export type RegisterResponse = {
  success: boolean;
  message: string;
};

type ModeratedCommunity = {
  communityId: number;
  role: string;
};
export type LoginResponse = {
  success: boolean;
  message: string;
  data: {
    username: string;
    avatar: string;
    accessToken: string;
    moderatedCommunities: ModeratedCommunity[];
  };
};

/* ____________________Community____________________ */
export type Moderators = {
  userId: number;
  username: string;
  avatar: string;
  role: string;
};
export type Community = {
  id: number;
  name: string;
  shortDescription: string;
  description: string;
  topic: string[];
  communityAvatar: string;
  coverImage: string;
  isPrivate: boolean;
  createdAt: string;
  totalMembers: number;
  moderators: Moderators[];
  isRequiresMemberApproval: boolean;
  isRequiresPostApproval: boolean;
  isRequestJoin: boolean;
  isFollow: boolean;
};

export type CommunityMember = {
  userId: number;
  username: string;
  avatar: string;
  karma: number;
  subscribedAt: string;
  status: string;
};

export type RecentCommunity = {
  id: number;
  name: string;
  communityAvatar: string;
  isPrivate: boolean;
  totalMembers: number;
};
/* ____________________End Community____________________ */

export type CommunityResponse = {
  success: boolean;
  message: string;
  data: Community[];
};

export type CreateCommunityResponse = {
  success: boolean;
  message: string;
};

/* ____________________Post____________________ */
export type Post = {
  id: number;
  communityId: number;
  community: {
    id: number;
    name: string;
    avatar: string;
    shortDescription: string;
  };
  authorId: number;
  author: {
    id: number;
    username: string;
    avatar: string;
  };
  title: string;
  type: string;
  content: string;
  mediaUrls: string[];
  tags: string[];
  status: string;
  vote: number;
  isVoted: boolean;
  commentCount: number;
  createdAt: string;
  updatedAt: string;
  pollData?: {
    question: string;
    options: Array<{
      id: number;
      text: string;
      votes: number;
      voters: number[];
    }>;
    multipleChoice: boolean;
    expiresAt?: string;
    totalVotes: number;
  };
};

export type RecentPost = {
  id: number;
  title: string;
  community: {
    id: number;
    name: string;
  };
  createdAt: string;
};
/* ____________________Reported Post____________________ */
export type Reporter = {
  id: number;
  username: string;
  avatar: string;
  reasons: string[];
  note: string;
  reportedAt?: string;
};

export type ReportedPost = {
  id: number;
  postId: number;
  postTitle: string;
  author: {
    id: number;
    username: string;
    avatar: string;
  };
  reporters: Reporter[];
  totalReports: number;
  lastReportedAt?: string;
};

/* ____________________Collected Post (Saved/Followed Post)____________________ */
export type CollectedPost = {
  postId: number;
  title: string;
  author: {
    id: number;
    username: string;
    avatar: string;
  };
  isFollowed: boolean;
  createdAt: string;
};

/* ____________________Tag____________________ */
export type Tag = {
  id: number;
  name: string;
};

/* ____________________Comment____________________ */
export type Comment = {
  id: number;
  postId: number;
  author: {
    id: number;
    username: string;
    avatar: string;
  };
  parentCommentId?: number;
  content: string;
  mediaUrl: string;
  vote: number;
  createdAt: string;
  updatedAt: string;
  replies: Comment[];
};

/* ____________________Image Response____________________ */
export type UploadImageResponse = {
  success: boolean;
  message: string;
  data: {
    url: string;
  }[];
};

/* ____________________Messages____________________ */
export type Message = {
  id: number;
  conversationId: number;
  sender: {
    id: number;
    username: string;
    avatar: string;
  };
  type: string;
  content: string;
  isRead: boolean;
  readAt: string | null;
  createdAt: string;
  attachments: string[];
  isDeleted: boolean;
};

export type Conversation = {
  id: number;
  otherUser: {
    id: number;
    username: string;
    avatar: string;
  };
  lastMessage: {
    content: string;
    isRead: boolean;
    sentAt: string;
    readAt: string | null;
  } | null;
  unreadCount: number;
  createdAt: string;
  updatedAt: string;
};

export type ConversationsResponse = {
  success: boolean;
  message: string;
  data: Conversation[];
  pagination: Pagination;
};

export type MessagesResponse = {
  success: boolean;
  message: string;
  data: Message[];
  pagination: Pagination;
};

export type SendMessageResponse = {
  success: boolean;
  message: string;
  data: Message & {
    conversationId: number;
  };
};

/* ____________________SSE Messages Event____________________ */
export type SSEMessageEvent = {
  conversationId: number;
  message: Message;
};

export type SSEConversationUpdatedEvent = {
  conversation: Conversation;
};

/* ____________________SSE Messages Event____________________ */
export type Badget = {
  badgeName: string;
  iconUrl: string;
  karma: number;
  monthYear: string; // "2025-11"
};

/* ____________________Link Metadata____________________ */
export type LinkMetadata = {
  title: string;
  description: string;
  images: string[];
  sitename: string;
  favicon: string;
  duration: number;
  domain: string;
  url: string;
  source: string;
};

/* ____________________Notifications____________________ */
export type NotificationAction =
  | 'get_post_new_comment'
  | 'get_comment_vote'
  | 'get_comment_reply'
  | 'get_post_vote'
  | 'post_approved'
  | 'post_deleted'
  | 'post_reported';

export type NotificationPayload = {
  postId?: number;
  commentId?: number;
  userName?: string;
  voteType?: boolean;
  userId?: number;
};

export type Notification = {
  id: number;
  body: string;
  action: NotificationAction;
  payload: NotificationPayload;
  isRead: boolean;
  createdAt: string;
};

export type NotificationsResponse = {
  success: boolean;
  message: string;
  data: Notification[];
  pagination: Pagination;
};

/* ____________________SSE Notification Event____________________ */
export type SSENotificationEvent = {
  notification: Notification;
  unreadCount: number;
};

/* ____________________Recent Search____________________ */
export type RecentSearch = {
  keyword: string;
  searchAt: string;
};
/* ____________________Settings____________________ */
export type Preference = {
  language: string;
  isStoreRecentPosts: boolean;
  isStoreRecentCommunities: boolean;
  autoplayMedia: boolean;
};

/* ____________________Settings____________________ */
export type SummayPost = {
  summary: string;
};
/*==========End Testing zone==========*/

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;
